version: "3.7"

services:

  postgres:
    build: codeInfrastructure/phpdocker/pgsql
    working_dir: /var/www
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/www
      - ./codeInfrastructure/pgsql/data:/var/lib/postgresql/data/pgdata/
    ports:
      - "6432:5432"
    #networks:
    #  - internal

  webserver:
    image: nginx:alpine
    container_name: $APP_NAME-webserver
    hostname: $APP_NAME-webserver
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./codeInfrastructure/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - $WEBSERVER_PORT:80
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    #networks:
    #  - internal

  php-fpm:
    build: codeInfrastructure/phpdocker/php-fpm
    container_name: $APP_NAME-php-fpm
    working_dir: /var/www
    volumes:
      - .:/var/www:cached
      - ./codeInfrastructure/phpdocker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./codeInfrastructure/phpdocker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - PHP_IDE_CONFIG=serverName=xdebugserver
    #networks:
    #  - internal

  php-fpm-cli:
    build:
      context: codeInfrastructure/phpdocker/php-fpm/cli
      dockerfile: Dockerfile
      args:
        - USER_ID
        - GROUP_ID
    container_name: $APP_NAME-php-fpm-cli
    working_dir: /var/www
    volumes:
      - .:/var/www:cached
    #networks:
    #  - internal

#networks:
#  internal:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 192.168.141.0/28

networks:
  default:
    name: "common-network"
    #external: true
